apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume
  namespace: spring
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db/
